/*
TSQL É UM BLOCO DE LINGUAGEM DE PROGRAMAÇÃO.
PROGRAMAS SÃO UNIDADES QUE POSEMSER CHAMADAS DE BLOCO ANÔNIMOS.
BLOCOS ANÔNIMOS NÃO RECEBEM NOME, POIS NÃO SÃO SALVOS NO BANCO. CRIAMOS BLOCOS ANÔNIMOS QUANDO IREMOS EXECUTA-LOS UMA SÓ VEZ OU TESTAR ALGO.
*/

DECLARE
	@CONTADOR
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO


DECLARE
	
	@V_NUMEMRO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '10062022'

BEGIN
	
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMEMRO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMEMRO)
	PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO

CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
GO
)

INSERT INTO CARROS VALUES('KA', 'FORD')
INSERT INTO CARROS VALUES('FIESTA', 'FORD')
INSERT INTO CARROS VALUES('PRISMA', 'FORD')
INSERT INTO CARROS VALUES('CLIO', 'RENAULT')
INSERT INTO CARROS VALUES('SANDERO', 'RENAULT')
INSERT INTO CARROS VALUES('CHEVETE', 'CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA', 'CHEVROLET')
INSERT INTO CARROS VALUES('PALIO', 'FIAT')
INSERT INTO CARROS VALUES('DOBLO', 'FIAT')
INSERT INTO CARROS VALUES('UNO', 'FIAT')
INSERT INTO CARROS VALUES('GOL', 'VOLKSWAGEN')
GO

DECLARE
	@CONT_FORD INT,
	@CONT_FIAT INT

BEGIN
	
	SET @CONT_FORD = (SELECT COUNT(*) FROM CARROS WHERE FABRICANTE = 'FORD')

	PRINT 'QUANTIDADE FORD' + CAST(@CONT_FORD AS VARCHAR)
END
GO

DECLARE
	
	@NUMERO INT = 5
BEGIN
	
	IF @NUMERO = 5
	PRINT 'ESSE NUMERO É IGUAL A 5'

	IF @NUMERO > 5
	PRINT 'ESSE NUMERO É MAIOR DO QUE 5'
	ELSE
		PRINT 'ESSE NÚMERO É MENOR DO QUE 5'
END
GO

DECLARE

	@I INT = 1
BEGIN

	WHILE(@I < 15)
	BEGIN
		PRINT 'VALOR DE @I = ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1

	END

END
GO