DECLARE @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50) 
DECLARE @LINHAS_BAIRRO INT, @CONTADOR INT
DECLARE @TABELA_BAIRROS TABLE ([BAIRRO] VARCHAR(50))

SET @CIDADE = 'Rio de Janeiro'
SET @CONTADOR = 0

SELECT @LINHAS_BAIRRO = COUNT(*) FROM (
SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]
WHERE CIDADE = @CIDADE) X

WHILE @CONTADOR < @LINHAS_BAIRRO
BEGIN
    SELECT DISTINCT @BAIRRO = BAIRRO FROM [TABELA DE CLIENTES]
    WHERE CIDADE = @CIDADE
    ORDER BY BAIRRO
    OFFSET @CONTADOR ROWS
    FETCH NEXT 1 ROWS ONLY
    INSERT INTO @TABELA_BAIRROS (BAIRRO) VALUES (@BAIRRO)
    SET @CONTADOR = @CONTADOR + 1
END
SELECT * FROM @TABELA_BAIRROS ORDER BY BAIRRO

SELECT BAIRRO
FROM [TABELA DE CLIENTES]
WHERE CIDADE = 'Rio de Janeiro'
ORDER BY BAIRRO

SELECT BAIRRO
FROM [TABELA DE CLIENTES]
WHERE CIDADE = 'Rio de Janeiro'
ORDER BY BAIRRO
OFFSET 3 ROWS
FETCH NEXT 1 ROWS ONLY;


--passando tabela como parametro

CREATE FUNCTION dbo.SomaValores (@tabela AS table (valor INT))
RETURNS FLOAT
AS
BEGIN
    DECLARE @soma FLOAT
    SET @soma = 0
    SELECT @soma = SUM(valor)
    FROM @tabela
    RETURN @soma
END


DECLARE @tabela AS table (valor INT)

INSERT INTO @tabela (valor)
VALUES (10), (20), (30)

SELECT dbo.SomaValores (@tabela)


