ALTER TABLE dbo.CLIENTES
  ADD CONSTRAINT pk_Clientes PRIMARY KEY(id_cliente);

ALTER TABLE dbo.LOCALIDADES
  ADD CONSTRAINT pk_Localidades PRIMARY KEY(id_cidade);

ALTER TABLE dbo.MECANICOS 
  ADD CONSTRAINT pk_Mecanicos PRIMARY KEY(id_mecanico);

ALTER TABLE dbo.ORDEM_SERVICO
  ADD CONSTRAINT pk_OrdemServico PRIMARY KEY(id_os);

--FOREIGN KEYS
ALTER TABLE dbo.ORDEM_SERVICO
  ADD CONSTRAINT fk_clientes FOREIGN KEY(ID_CLIENTE)
      REFERENCES dbo.CLIENTES(ID_CLIENTE);

ALTER TABLE dbo.ORDEM_SERVICO
  ADD CONSTRAINT fk_localidades FOREIGN KEY(id_cidade)
      REFERENCES dbo.LOCALIDADES(ID_CIDADE);

ALTER TABLE dbo.ORDEM_SERVICO
  ADD CONSTRAINT fk_Mecanicos FOREIGN KEY(id_mecanico)
      REFERENCES dbo.MECANICOS(ID_MECANICO);

--------------------------
select S.ID_OS, S.SERVICO, 
       S.ID_CLIENTE, C.NOME_CLIENTE,
	   S.ID_CIDADE, L.NM_MUNICIPIO,
	   S.ID_MECANICO, M.NOME_MECANICO
  from dbo.ORDEM_SERVICO S
       INNER JOIN dbo.CLIENTES C on C.ID_CLIENTE = S.ID_CLIENTE
	   INNER JOIN dbo.LOCALIDADES L on L.ID_CIDADE = S.ID_CIDADE
	   INNER JOIN dbo.MECANICOS M on M.ID_MECANICO = S.ID_MECANICO
 where m.NOME_MECANICO like '%TROVATO%';

SELECT * FROM DBO.ORDEM_SERVICO;