SELECT 
	FLAN.CODCOLIGADA AS 'COLIGADA',
	FLAN.IDLAN AS 'COD_LANCAMENTO',
	FLAN.CODCCUSTO AS 'CCUSTOLAN',

	FCFO.NOME AS 'NOME_CLIENTE _FORNECEDOR',
	FCFO.CODCFO AS 'COD_CLIENTE_FORNECEDOR',
	FCFO.CGCCFO AS 'CNPJ_CLIENTE_FORNECEDOR',

	GCCUSTO.NOME AS 'NOME_CCUSTO',
	GCCUSTO.CODCCUSTO AS 'COD_CCUSTO',

	CONVERT(VARCHAR(10), FLANBAIXA.DATABAIXA, 103) AS 'DATA_BAIXA',
	CASE
		WHEN FLANBAIXA.PAGREC = 2 THEN ISNULL(FLANBAIXA.VALORBAIXA,0)  *-1 
		ELSE ISNULL(FLANBAIXA.VALORBAIXA,0) 
	END AS 'VALOR_BAIXADO',
	FLANBAIXA.CODCXA AS 'COD_CONTA_CAIXA',
	FCXA.DESCRICAO AS 'DESC_CONTA_CAIXA',

	FXCX.NUMERODOCUMENTO AS 'NUM_DOC_EXTRATO_CAIXA',
	FXCX.DATA AS 'DATA_EXTRATO_CAIXA',
	FXCX.VALOR AS 'VALOR_EXTRATO_CAIXA',

	TTBORCAMENTO.CODTBORCAMENTO AS 'COD_NAT_FINANCEIRA',
	TTBORCAMENTO.DESCRICAO AS 'NAT_FINANCEIRA'

FROM
	FLAN (NOLOCK)  
		INNER JOIN FCFO(NOLOCK)
		ON FLAN.CODCOLCFO = FCFO.CODCOLIGADA
		AND FLAN.CODCFO = FCFO.CODCFO 
		INNER JOIN GCCUSTO(NOLOCK)
		ON FLAN.CODCOLIGADA = GCCUSTO.CODCOLIGADA
		AND FLAN.CODCCUSTO = GCCUSTO.CODCCUSTO
		INNER JOIN FLANRATCCU(NOLOCK)
							 INNER JOIN TTBORCAMENTO(NOLOCK)
							 ON FLANRATCCU.CODCOLNATFINANCEIRA = TTBORCAMENTO.CODCOLIGADA
							 AND FLANRATCCU.CODNATFINANCEIRA = TTBORCAMENTO.CODTBORCAMENTO
		ON FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA
		AND FLAN.IDLAN = FLANRATCCU.IDLAN
		LEFT JOIN FXCX(NOLOCK)
		ON FLAN.CODCOLIGADA = FXCX.CODCOLIGADA
		AND FLAN.IDLAN = FXCX.IDLAN 
		INNER JOIN FLANBAIXA(NOLOCK)
							INNER JOIN FLANBAIXARATCCU(NOLOCK)
							ON FLANBAIXA.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA
							AND FLANBAIXA.IDLAN = FLANBAIXARATCCU.IDLAN
							AND FLANBAIXA.IDBAIXA = FLANBAIXARATCCU.IDBAIXA
							INNER JOIN FCXA(NOLOCK)
							ON FLANBAIXA.CODCOLIGADA = FCXA.CODCOLIGADA
							AND FLANBAIXA.CODCXA = FCXA.CODCXA 
		ON FLAN.IDLAN = FLANBAIXA.IDLAN
		AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
		INNER JOIN GBANCO(NOLOCK)
		ON FLAN.CNABBANCO = GBANCO.NUMBANCO
WHERE
	FLAN.CODCOLIGADA = 1
	AND FLAN.DATAVENCIMENTO >= '01/01/2021'
	AND FLAN.DATAVENCIMENTO <= '04/01/2021'


/*
	SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE 'FCXA'

	SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE 'FLAN' AND CHILDTABLE LIKE 'GCCUSTO'

	SELECT * FROM GDIC WHERE TABELA LIKE 'GCCUSTO'

	SELECT * FROM GDIC WHERE DESCRICAO LIKE '%CENTROS DE CUSTO%' AND COLUNA LIKE '#'

	SELECT * FROM GBANCO
*/ 


/*
	TABELAS NECESSÁRIAS PARA UM FLUXO DE CAIXA

	1- CLIENTE E FORNECEDOR (FCFO)
	2- CENTRO DE CUSTO (GCCUSTO)
	3- NATUREZA FINANCEIRA (TTBORCAMENTO)
	4- EXTRATO DE CAIXA (FXCX)
	5- BAIXA (FLANBAIXA)
	6- RATEIO DE BAIXO POR CENTRO DE CUSTO (FLANBAIXARATCCU)
	7- CONTA CAIXA (FCXA)

*/

/*
	SELECT 
	PPESSOA.NOME
	
FROM
	SALUNO
		INNER JOIN FCFO(NOLOCK)
		ON SALUNO.CODCOLCFO = FCFO.CODCOLIGADA
		AND SALUNO.CODCFO = FCFO.CODCFO
		INNER JOIN PPESSOA(NOLOCK)
		ON SALUNO.CODPESSOA = PPESSOA.CODIGO
		INNER JOIN SMATRICPL(NOLOCK)
							INNER JOIN SHABILITACAOFILIAL(NOLOCK)
														INNER JOIN SHABILITACAO(NOLOCK)
																			INNER JOIN SCURSO(NOLOCK)
																			ON SHABILITACAO.CODCOLIGADA = SCURSO.CODCOLIGADA
																			AND SHABILITACAO.CODCURSO = SCURSO.CODCURSO
														ON SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAO.CODCOLIGADA
														AND SHABILITACAOFILIAL.CODCURSO = SHABILITACAO.CODCURSO
														AND SHABILITACAOFILIAL.CODHABILITACAO = SHABILITACAO.CODHABILITACAO
							ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
							AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
							INNER JOIN SCONTRATO(NOLOCK)
												INNER JOIN SPARCELA(NOLOCK)
																INNER JOIN SSERVICO(NOLOCK)
																ON SPARCELA.CODCOLIGADA = SSERVICO.CODCOLIGADA
																AND SPARCELA.CODSERVICO = SSERVICO.CODSERVICO
																INNER JOIN SLAN(NOLOCK)
																			  INNER JOIN FLAN(NOLOCK)
																							INNER JOIN FLANBOLETO
																										INNER JOIN FBOLETO
																										ON FLANBOLETO.CODCOLIGADA = FBOLETO.CODCOLIGADA
																										AND FLANBOLETO.IDBOLETO = FBOLETO.IDBOLETO
																							ON FLAN.CODCOLIGADA = FLANBOLETO.CODCOLIGADA
																							AND FLAN.IDLAN = FLANBOLETO.IDLAN
																			  ON SLAN.IDLAN = FLAN.IDLAN
																			  AND SLAN.CODCOLIGADA = FLAN.CODCOLIGADA
																ON SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA
																AND SPARCELA.IDPARCELA = SLAN.IDPARCELA
												ON SCONTRATO.CODCOLIGADA = SPARCELA.CODCOLIGADA
												AND SCONTRATO.RA = SPARCELA.RA
												AND SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
												AND SCONTRATO.IDPERLET = SPARCELA.IDPERLET
							ON SMATRICPL.CODCOLIGADA = SCONTRATO.CODCOLIGADA
							AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET
							AND SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
							AND SMATRICPL.RA = SCONTRATO.RA
		ON SALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SALUNO.RA = SALUNO.RA
WHERE
	--FCFO.PAGREC = 2
	SALUNO.CODCOLIGADA = 1
	AND SHABILITACAOFILIAL.CODHABILITACAO = 23
	AND SMATRICPL.IDPERLET in (SELECT
								SPLETIVO.IDPERLET
							  FROM
								SPLETIVO
							  WHERE
								SPLETIVO.CODCOLIGADA   = SALUNO.CODCOLIGADA
								AND SPLETIVO.CODPERLET = 2022)
	AND SCONTRATO.CODPLANOPGTO IS NOT NULL
	AND SMATRICPL.CODSTATUS    IN('1','6')
	AND SHABILITACAOFILIAL.CODHABILITACAO BETWEEN '01' AND '89'
	AND SHABILITACAOFILIAL.CODHABILITACAO NOT IN ('72')
	AND SHABILITACAOFILIAL.CODCURSO <> 'GB' 
	AND SHABILITACAOFILIAL.CODCURSO <> 'CF'
	AND SHABILITACAOFILIAL.CODCURSO <> 'DM'





/*
	SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE 'FLAN'
*/
*/