
/*==================================================================================*/
/*SUBQUERIES OU SUBSELECT*/
/*==================================================================================*/


SELECT * FROM VENDEDORES;

SELECT MIN(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/*Trabalhando com linhas
total e a média de cada vendedor
*/

SELECT VENDEDOR.NOME,
	   VENDEDOR.MARCO,
	   VENDEDOR.JANEIRO,
	   VENDEDOR.FEVEREIRO,
	   (VENDEDOR.JANEIRO + VENDEDOR.FEVEREIRO + FEVEREIRO.MARCO) AS TOTAL,
	   TRUNCATE(VENDEDOR.JANEIRO + VENDEDOR.FEVEREIRO + FEVEREIRO.MARCO, 2) AS MÉDIA
FROM VENDEDORES;