CREATE DATABASE COMERCIO;


USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50), UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE


	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CELL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,


	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);


INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','4782873943');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','459384508903');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','F','ELAINE@LOBO.COM','7847394758');
INSERT INTO CLIENTE VALUES(NULL,'FABRICIO','F','FABRICIOAIG.COM','4782873943');
INSERT INTO CLIENTE VALUES(NULL,'EMANUEL','F','EMANULEIG.COM','4782873943');
INSERT INTO CLIENTE VALUES(NULL,'ROGÉRIO','F','ROGÉRIOIG.COM','4782873943');



INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',15);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',16);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B.HORIZONTE','MG',21);



INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',11);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',11);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',11);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',11);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',11);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',15);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',15);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',15);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',15);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',16);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',16);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',20);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',20);
INSERT INTO TELEFONE VALUES(NULL,'RES','853080439',21);


/*==================================================================================*/
/*JOIN*/
/*==================================================================================*/


/*RELATÓRIO GERAL DE TODOS OS CLIENTES (TELEFONES E ENDERECO)*/


SELECT
		CLIENTE.IDCLIENTE,
		CLIENTE.NOME,
		CLIENTE.SEXO,
		CLIENTE.EMAIL,
		CLIENTE.CPF,
		ENDERECO.RUA,
		ENDERECO.BAIRRO,
		ENDERECO.CIDADE,
		ENDERECO.ESTADO,
		TELEFONE.TIPO,
		TELEFONE.NUMERO



FROM CLIENTE 
		INNER JOIN ENDERECO
				ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
		INNER JOIN TELEFONE
				ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE




/*RELATÓRIO DE HOMENS*/


FROM CLIENTE 
		INNER JOIN ENDERECO
				ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
		INNER JOIN TELEFONE
				ON IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'M';



/*UPDATE*/
UPDATE CLIENTE SET SEXO = 'F'
WHERE IDCLIENTE IN(12, 12, 18, 19);

/*MULHERES*/

FROM CLIENTE 
		INNER JOIN ENDERECO
				ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
		INNER JOIN TELEFONE
				ON IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'F';


/*QUANTIDADE DE HOMENS E MULHERES*/

SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE
GROUP BY SEXO;

SELECT 
		CLIENTE.IDCLIENTE, 
		CLIENTE.EMAIL, 
		CLIENTE.NOME,
		CLIENTE.SEXO,
		CLIENTE.TELEFONE

FROM CLIENTE
			INNER JOIN ENDERECO
					ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
			INNER JOIN TELEFONE
					ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE

WHERE SEXO = 'F';
AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
AND (TIPO = 'RES' OR 'COM');


SELECT 
		CLIENTE.NOME, 
		CLIENTE.EMAIL, 
		TELEFONE.NUMERO,
		

FROM CLIENTE
			INNER JOIN ENDERECO
					ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
			INNER JOIN TELEFONE
					ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE

WHERE TIPO = 'CEL' AND ESTADO = 'RJ';

SELECT 
		CLIENTE.NOME, 
		CLIENTE.EMAIL, 
		TELEFONE.NUMERO,
	
FROM CLIENTE
			INNER JOIN ENDERECO
					ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
			INNER JOIN TELEFONE
					ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE

WHERE TIPO = 'CEL' AND ESTADO = 'SP';

SELECT 
		CLIENTE.NOME,
		IFNULL(CLIENTE.EMAIL,'NÃO TEM EMAIL') AS 'EMAIL',
		ENDERECO.ESTADO,
		TELEFONE.NUMERO
FROM CLIENTE
			INNER JOIN ENDERECO
					ON CLIENTE.IDCLIENTE = CLIENTE.ID_CLIENTE
			INNER JOIN TELEFONE
					ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE



CREATE VIEW RELATORIO AS
SELECT 
		CLIENTE.IDCLIENTE, 
		CLIENTE.EMAIL, 
		CLIENTE.NOME,
		CLIENTE.SEXO,
		CLIENTE.TELEFONE

FROM CLIENTE
			INNER JOIN ENDERECO
					ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
			INNER JOIN TELEFONE
					ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE

SELECT * FROM RELATORIO;

"{
	SHOW DATABASES,
	SHOW TABLES,
	
}"   

/*FUNCOES DE AGREGACOES NUMERICAS*/

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2),
);


INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS','M',74379.78,6456.65,343222.77);
INSERT INTO VENDEDORES VALUES(NULL, 'MARIA','F',56456.78,23645645456.65,54355.77);
INSERT INTO VENDEDORES VALUES(NULL, 'ANTONIO','M',645645.78,645645.65,54353.77);
INSERT INTO VENDEDORES VALUES(NULL, 'CLARA','F',456456.78,54353.65,4435.77);
INSERT INTO VENDEDORES VALUES(NULL, 'ANDERSON','M',456456.78,23456.65,53453.77);
INSERT INTO VENDEDORES VALUES(NULL, 'IVONE','F',67567.78,43534.65,5434.77);
INSERT INTO VENDEDORES VALUES(NULL, 'JOAO','M',645456.78,543543.65,543553.77);
INSERT INTO VENDEDORES VALUES(NULL, 'CELIA','F',65356.78,543534.65,543543.77);

/*MAIOR DE MARÇO*/

SELECT MAX(MARCO) AS MAIOR MARCO
FROM VENDEDORES;

/*MENOR DE JANEIRO*/

SELECT MIN(JANEIRO) AS MENOR JANEIRO
FROM VENDEDORES;

/*MAIOR FEVEREIRO*/

SELECT MAX(FEVEREIRO) AS MENOR FEVEREIRO
FROM VENDEDORES;

/*MEDIA DE TODOS OS MESES*/

SELECT AVG(VENDEDORES.JANEIRO),
	   AVG(VENDEDORES.FEVEREIRO),
	   AVG(VENDEDORES.MARCO)

FROM VENDEDORES;

/*==================================================================================*/
/*SUBQUERIES OU SUBSELECT*/
/*==================================================================================*/


SELECT * FROM VENDEDORES;

SELECT MIN(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME, MARCO FROM VENDEDORES;
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/*Trabalhando com linhas
total e a média de cada vendedor
*/

SELECT VENDEDOR.NOME,
	   VENDEDOR.MARCO,
	   VENDEDOR.JANEIRO,
	   VENDEDOR.FEVEREIRO,
	   (VENDEDOR.JANEIRO + VENDEDOR.FEVEREIRO + FEVEREIRO.MARCO) AS TOTAL,
	   TRUNCATE(VENDEDOR.JANEIRO + VENDEDOR.FEVEREIRO + FEVEREIRO.MARCO, 2) AS MÉDIA
FROM VENDEDORES;



/*=======================*/



