

/*PROCEDURES COM PARAMETROS*/

SELECT 10 + 10 AS CONTA;

/*QUANDO FIZER UMA PROCEDURE TROCAR O DELIMITADOR ";" POR OUTRO  QUALQUER, POR EXEMPLO "$"*/

DELIMITER $

CREATE PROCEDURE CONTA()
BEGIN
	
	SELECT 10 + 10 AS CONTA;

END
$

CALL CONTA();

DROP PROCEDURE CONTA;

DELIMITER $

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
	SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$

CALL CONTA(100, 50)$
CALL CONATA(234234, 4234)$
CALL CONATA(345435, 543534)$
CALL CONATA(43543543, 534543)$


CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR(10, 2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, "JAVA", 30,500.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BACO DE DADOS', 40, 700.00);

SELECT * CURSOS;

DELIMITER #;

STATUS /*STATUS <== PARA VER COMO TÁ O DELIMITER*/


CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(30), P_PRECO FLOAT(10,2))
BEGIN 

	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);

END
#

DELIMITER ;

CALL CAD_CURSO("BI SQL SERVER", 35, 3000.00);
CALL CAD_CURSO("POWER BI ", 20, 1000.00);
CALL CAD_CURSO("TABLEAU", 30, 3200.00);
CALL CAD_CURSO("JAVA", 40, 3500.00);
CALL CAD_CURSO("NODE JS", 30, 2200.00);




